import type { PaperStyleDef } from "./types";

function ruled(
  id: string,
  name: string,
  description: string,
  opts: {
    bg: string;
    spacing: number;
    color: string;
    margin?: PaperStyleDef["margin"];
    texture?: PaperStyleDef["texture"];
    category?: PaperStyleDef["category"];
    thickness?: number;
  },
): PaperStyleDef {
  return {
    id,
    name,
    category: opts.category || "ruled",
    description,
    bg: opts.bg,
    pattern: {
      kind: "ruled",
      spacing: opts.spacing,
      color: opts.color,
      thickness: opts.thickness ?? 1,
      startOffset: 48,
    },
    margin: opts.margin,
    texture: opts.texture || "none",
    dark: false,
    printable: true,
  };
}

export const PAPER_STYLES: PaperStyleDef[] = [
  // —— Ruled / Notebook (1–10) ——
  ruled("classic-blue-ruled", "Classic Blue Ruled", "Everyday notebook with soft blue writing lines.", {
    bg: "#fffef9",
    spacing: 32,
    color: "rgba(90, 130, 190, 0.35)",
    margin: { left: 52, color: "rgba(210, 70, 70, 0.4)", width: 1 },
  }),
  ruled("college-ruled", "College Ruled", "Standard college spacing for dense study notes.", {
    bg: "#ffffff",
    spacing: 28,
    color: "rgba(100, 145, 200, 0.4)",
    margin: { left: 56, color: "rgba(200, 60, 60, 0.45)", width: 1.25 },
  }),
  ruled("wide-ruled", "Wide Ruled", "Wider line spacing for younger students or large handwriting.", {
    bg: "#fffcf5",
    spacing: 40,
    color: "rgba(95, 140, 195, 0.38)",
    margin: { left: 48, color: "rgba(205, 75, 75, 0.4)", width: 1 },
  }),
  ruled("narrow-ruled", "Narrow Ruled", "Tight spacing for compact revision pages.", {
    bg: "#fafbff",
    spacing: 22,
    color: "rgba(110, 150, 205, 0.32)",
    margin: { left: 44, color: "rgba(190, 70, 70, 0.35)", width: 1 },
  }),
  ruled("red-margin-notebook", "Red Margin Notebook", "Bright red margin with classic ruled lines.", {
    bg: "#fffdf8",
    spacing: 30,
    color: "rgba(120, 145, 175, 0.32)",
    margin: { left: 60, color: "rgba(220, 40, 40, 0.55)", width: 1.5 },
  }),
  ruled("blue-margin-notebook", "Blue Margin Notebook", "Blue margin line with cool-toned ruling.", {
    bg: "#f8fbff",
    spacing: 30,
    color: "rgba(80, 130, 190, 0.35)",
    margin: { left: 58, color: "rgba(50, 110, 190, 0.5)", width: 1.5 },
  }),
  {
    id: "double-margin-notebook",
    name: "Double Margin Notebook",
    category: "ruled",
    description: "Two vertical margins for structured annotation.",
    bg: "#fffefb",
    pattern: { kind: "ruled", spacing: 30, color: "rgba(100, 140, 180, 0.32)", startOffset: 48 },
    margin: { left: 48, color: "rgba(200, 70, 70, 0.4)", width: 1, dual: 72 },
    texture: "none",
    dark: false,
    printable: true,
  },
  ruled("soft-grey-ruled", "Soft Grey Ruled", "Quiet grey lines on pale paper.", {
    bg: "#f7f7f5",
    spacing: 32,
    color: "rgba(120, 120, 120, 0.28)",
    margin: { left: 50, color: "rgba(140, 140, 140, 0.35)", width: 1 },
  }),
  ruled("cream-notebook", "Cream Notebook", "Warm cream stock with gentle blue rules.", {
    bg: "#faf3e3",
    spacing: 32,
    color: "rgba(130, 150, 180, 0.33)",
    margin: { left: 54, color: "rgba(190, 90, 80, 0.4)", width: 1 },
    texture: "grain",
  }),
  ruled("legal-ruled", "Legal Ruled", "Legal-pad spacing with a warm yellow tone.", {
    bg: "#fff7c8",
    spacing: 34,
    color: "rgba(90, 130, 80, 0.28)",
    margin: { left: 64, color: "rgba(200, 60, 50, 0.5)", width: 1.5 },
    category: "ruled",
  }),

  // —— Grid / Graph (11–20) ——
  {
    id: "small-graph",
    name: "Small Graph",
    category: "grid",
    description: "Fine 5mm-style squares for precise diagrams.",
    bg: "#ffffff",
    pattern: { kind: "grid", size: 12, color: "rgba(100, 150, 200, 0.28)" },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "medium-graph",
    name: "Medium Graph",
    category: "grid",
    description: "Balanced graph paper for science and maths.",
    bg: "#fcfdff",
    pattern: { kind: "grid", size: 18, color: "rgba(90, 140, 190, 0.3)" },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "large-graph",
    name: "Large Graph",
    category: "grid",
    description: "Larger squares for sketches and planning.",
    bg: "#fffefc",
    pattern: { kind: "grid", size: 28, color: "rgba(110, 145, 185, 0.32)" },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "engineering-grid",
    name: "Engineering Grid",
    category: "grid",
    description: "Minor and major grid lines like engineering pads.",
    bg: "#f4faf4",
    pattern: {
      kind: "grid",
      size: 10,
      color: "rgba(70, 140, 90, 0.2)",
      majorEvery: 5,
      majorColor: "rgba(50, 120, 70, 0.4)",
      majorThickness: 1.2,
    },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "math-grid",
    name: "Math Grid",
    category: "grid",
    description: "Clean coordinates-friendly grid for equations.",
    bg: "#fafcff",
    pattern: {
      kind: "grid",
      size: 16,
      color: "rgba(80, 120, 190, 0.25)",
      majorEvery: 4,
      majorColor: "rgba(60, 100, 180, 0.42)",
    },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "isometric-grid",
    name: "Isometric Grid",
    category: "grid",
    description: "Isometric triangles for 3D sketches.",
    bg: "#ffffff",
    pattern: { kind: "isometric", size: 24, color: "rgba(100, 130, 170, 0.28)" },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "dot-grid",
    name: "Dot Grid",
    category: "grid",
    description: "Classic dotted notebook for flexible layouts.",
    bg: "#fffcf7",
    pattern: { kind: "dots", gap: 22, radius: 1.1, color: "rgba(90, 90, 100, 0.35)" },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "fine-dot-grid",
    name: "Fine Dot Grid",
    category: "grid",
    description: "Denser dots for detailed planning pages.",
    bg: "#ffffff",
    pattern: { kind: "dots", gap: 14, radius: 0.85, color: "rgba(100, 100, 110, 0.32)" },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "bullet-journal-grid",
    name: "Bullet Journal Grid",
    category: "grid",
    description: "Soft cream with calm bullet-journal dots.",
    bg: "#faf6ef",
    pattern: { kind: "dots", gap: 20, radius: 1.05, color: "rgba(120, 100, 80, 0.3)" },
    texture: "grain",
    dark: false,
    printable: true,
  },
  {
    id: "faint-square-grid",
    name: "Faint Square Grid",
    category: "grid",
    description: "Very light squares that stay out of the way.",
    bg: "#ffffff",
    pattern: { kind: "grid", size: 20, color: "rgba(140, 140, 150, 0.14)" },
    texture: "none",
    dark: false,
    printable: true,
  },

  // —— School / Study (21–30) ——
  ruled("school-exercise-book", "School Exercise Book", "Familiar exercise-book blue lines and margin.", {
    bg: "#fffef6",
    spacing: 30,
    color: "rgba(70, 120, 190, 0.4)",
    margin: { left: 56, color: "rgba(210, 50, 50, 0.5)", width: 1.25 },
    category: "school",
  }),
  {
    id: "exam-answer-sheet",
    name: "Exam Answer Sheet",
    category: "school",
    description: "Header band, answer lines, and footer space.",
    bg: "#ffffff",
    pattern: {
      kind: "exam",
      spacing: 30,
      color: "rgba(80, 80, 90, 0.35)",
      headerHeight: 72,
      footerHeight: 40,
    },
    margin: { left: 48, color: "rgba(180, 60, 60, 0.35)", width: 1 },
    texture: "none",
    dark: false,
    printable: true,
  },
  ruled("revision-sheet", "Revision Sheet", "Pale green revision paper with soft rules.", {
    bg: "#f3faf3",
    spacing: 30,
    color: "rgba(80, 140, 100, 0.3)",
    margin: { left: 50, color: "rgba(60, 130, 80, 0.4)", width: 1 },
    category: "school",
  }),
  ruled("homework-sheet", "Homework Sheet", "Simple homework page with clear spacing.", {
    bg: "#fffdf9",
    spacing: 34,
    color: "rgba(110, 140, 180, 0.3)",
    margin: { left: 52, color: "rgba(200, 80, 70, 0.4)", width: 1 },
    category: "school",
  }),
  ruled("study-notes", "Study Notes", "Soft lavender-tint ruled paper for daily notes.", {
    bg: "#faf7ff",
    spacing: 32,
    color: "rgba(140, 120, 180, 0.28)",
    margin: { left: 54, color: "rgba(160, 100, 170, 0.35)", width: 1 },
    category: "school",
  }),
  {
    id: "cornell-notes",
    name: "Cornell Notes",
    category: "school",
    description: "Cue column, notes area, and summary footer.",
    bg: "#ffffff",
    pattern: {
      kind: "cornell",
      spacing: 28,
      color: "rgba(100, 110, 130, 0.35)",
      cueWidth: 140,
      summaryHeight: 120,
    },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "cornell-minimal",
    name: "Cornell Minimal",
    category: "school",
    description: "Lighter Cornell layout with quieter dividers.",
    bg: "#fcfcfa",
    pattern: {
      kind: "cornell",
      spacing: 30,
      color: "rgba(130, 130, 140, 0.22)",
      cueWidth: 120,
      summaryHeight: 96,
    },
    texture: "none",
    dark: false,
    printable: true,
  },
  ruled("vocabulary-sheet", "Vocabulary Sheet", "Wide lines for word lists and definitions.", {
    bg: "#fff9f2",
    spacing: 36,
    color: "rgba(180, 140, 100, 0.3)",
    margin: { left: 70, color: "rgba(180, 120, 70, 0.4)", width: 1 },
    category: "school",
  }),
  {
    id: "flashcard-paper",
    name: "Flashcard Paper",
    category: "school",
    description: "Card-like panels for Q&A study blocks.",
    bg: "#f7f9fc",
    pattern: { kind: "grid", size: 96, color: "rgba(120, 140, 170, 0.22)", thickness: 1.2 },
    texture: "none",
    dark: false,
    printable: true,
  },
  ruled("assignment-sheet", "Assignment Sheet", "Formal assignment layout with firm margin.", {
    bg: "#ffffff",
    spacing: 30,
    color: "rgba(90, 100, 120, 0.3)",
    margin: { left: 64, color: "rgba(60, 70, 90, 0.45)", width: 1.5 },
    category: "school",
  }),

  // —— Professional / Office (31–40) ——
  {
    id: "clean-office-paper",
    name: "Clean Office Paper",
    category: "professional",
    description: "Plain bright white for professional write-ups.",
    bg: "#ffffff",
    pattern: { kind: "none" },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "letterhead-minimal",
    name: "Letterhead Minimal",
    category: "professional",
    description: "Subtle header rule suggesting letterhead space.",
    bg: "#ffffff",
    pattern: { kind: "exam", spacing: 999, color: "transparent", headerHeight: 64, footerHeight: 0 },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "legal-pad",
    name: "Legal Pad",
    category: "professional",
    description: "Yellow legal pad with red left margin.",
    bg: "#fff4a8",
    pattern: { kind: "legal", spacing: 32, color: "rgba(70, 120, 70, 0.3)", marginColor: "rgba(200, 50, 50, 0.55)" },
    margin: { left: 68, color: "rgba(200, 50, 50, 0.55)", width: 1.5 },
    texture: "grain",
    dark: false,
    printable: true,
  },
  ruled("memo-paper", "Memo Paper", "Compact memo ruling on cool grey paper.", {
    bg: "#f3f4f6",
    spacing: 26,
    color: "rgba(110, 120, 140, 0.28)",
    margin: { left: 40, color: "rgba(90, 100, 120, 0.35)", width: 1 },
    category: "professional",
  }),
  ruled("meeting-notes", "Meeting Notes", "Business-friendly ruled cream for meetings.", {
    bg: "#faf8f2",
    spacing: 30,
    color: "rgba(120, 130, 140, 0.28)",
    margin: { left: 52, color: "rgba(100, 110, 130, 0.4)", width: 1 },
    category: "professional",
  }),
  {
    id: "project-notes",
    name: "Project Notes",
    category: "professional",
    description: "Light project grid for tasks and sketches.",
    bg: "#f8fafc",
    pattern: { kind: "grid", size: 22, color: "rgba(100, 120, 150, 0.18)" },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "plain-professional",
    name: "Plain Professional",
    category: "professional",
    description: "Unlined ivory sheet for clean printouts.",
    bg: "#fbfaf7",
    pattern: { kind: "none" },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "cream-office",
    name: "Cream Office",
    category: "professional",
    description: "Warm cream office stock without lines.",
    bg: "#f7f0e2",
    pattern: { kind: "none" },
    texture: "grain",
    dark: false,
    printable: true,
  },
  ruled("executive-ruled", "Executive Ruled", "Refined dark rules on soft white.", {
    bg: "#f9f9f7",
    spacing: 30,
    color: "rgba(70, 70, 75, 0.28)",
    margin: { left: 58, color: "rgba(50, 50, 55, 0.4)", width: 1.25 },
    category: "professional",
  }),
  {
    id: "faint-professional-grid",
    name: "Faint Professional Grid",
    category: "professional",
    description: "Barely-there grid for structured office notes.",
    bg: "#ffffff",
    pattern: { kind: "grid", size: 24, color: "rgba(120, 130, 145, 0.12)" },
    texture: "none",
    dark: false,
    printable: true,
  },

  // —— Natural / Paper Texture (41–48) ——
  {
    id: "warm-ivory",
    name: "Warm Ivory",
    category: "texture",
    description: "Warm ivory sheet with soft fiber texture.",
    bg: "#f6ecd8",
    pattern: { kind: "none" },
    texture: "fiber",
    dark: false,
    printable: true,
  },
  {
    id: "soft-cream",
    name: "Soft Cream",
    category: "texture",
    description: "Gentle cream paper with mild grain.",
    bg: "#faf1df",
    pattern: { kind: "none" },
    texture: "grain",
    dark: false,
    printable: true,
  },
  {
    id: "recycled-paper",
    name: "Recycled Paper",
    category: "texture",
    description: "Speckled recycled look that stays readable.",
    bg: "#ebe6d8",
    pattern: { kind: "none" },
    texture: "recycled",
    dark: false,
    printable: true,
  },
  {
    id: "kraft-paper",
    name: "Kraft Paper",
    category: "texture",
    description: "Brown kraft stationery with subtle grain.",
    bg: "#d2b48c",
    ink: "#2a1f14",
    pattern: { kind: "none" },
    texture: "kraft",
    dark: false,
    printable: true,
  },
  {
    id: "subtle-fiber-paper",
    name: "Subtle Fiber Paper",
    category: "texture",
    description: "Fine fiber wisps over pale stock.",
    bg: "#f5f2ea",
    pattern: { kind: "ruled", spacing: 34, color: "rgba(150, 140, 120, 0.15)", startOffset: 48 },
    texture: "fiber",
    dark: false,
    printable: true,
  },
  {
    id: "vintage-notebook",
    name: "Vintage Notebook",
    category: "texture",
    description: "Aged notebook with soft blue rules.",
    bg: "#f0e4c8",
    pattern: { kind: "ruled", spacing: 30, color: "rgba(100, 130, 160, 0.28)", startOffset: 48 },
    margin: { left: 52, color: "rgba(170, 90, 70, 0.35)", width: 1 },
    texture: "aged",
    dark: false,
    printable: true,
  },
  {
    id: "aged-paper",
    name: "Aged Paper",
    category: "texture",
    description: "Yellowed page with gentle age marks.",
    bg: "#e8d5a8",
    pattern: { kind: "none" },
    texture: "aged",
    dark: false,
    printable: true,
  },
  {
    id: "handmade-paper",
    name: "Handmade Paper",
    category: "texture",
    description: "Handmade sheet with organic fiber texture.",
    bg: "#f3ecdf",
    pattern: { kind: "none" },
    texture: "handmade",
    dark: false,
    printable: true,
  },

  // —— Minimal / Special (49–53) ——
  {
    id: "plain-white",
    name: "Plain White",
    category: "minimal",
    description: "Blank white paper with no ruling.",
    bg: "#ffffff",
    pattern: { kind: "none" },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "plain-off-white",
    name: "Plain Off-White",
    category: "minimal",
    description: "Soft off-white blank page.",
    bg: "#f7f5f0",
    pattern: { kind: "none" },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "minimal-grey",
    name: "Minimal Grey",
    category: "minimal",
    description: "Quiet grey blank page for modern notes.",
    bg: "#eceff2",
    pattern: { kind: "none" },
    texture: "none",
    dark: false,
    printable: true,
  },
  {
    id: "dark-paper",
    name: "Dark Paper",
    category: "minimal",
    description: "Dark study paper with faint light rules.",
    bg: "#1f2430",
    ink: "#e8eaf0",
    pattern: { kind: "ruled", spacing: 32, color: "rgba(255,255,255,0.08)", startOffset: 48 },
    margin: { left: 52, color: "rgba(255,180,180,0.25)", width: 1 },
    texture: "grain",
    dark: true,
    printable: true,
  },
  {
    id: "blackboard-study-paper",
    name: "Blackboard Study Paper",
    category: "minimal",
    description: "Chalkboard-inspired dark paper for study sketches.",
    bg: "#243028",
    ink: "#f2f5e8",
    pattern: { kind: "grid", size: 28, color: "rgba(255,255,255,0.07)" },
    texture: "chalkboard",
    dark: true,
    printable: true,
  },
];

export const PAPER_STYLE_IDS = PAPER_STYLES.map((p) => p.id);

export function getPaperStyle(id?: string | null): PaperStyleDef | undefined {
  if (!id) return undefined;
  return PAPER_STYLES.find((p) => p.id === id);
}

export function resolvePaperStyle(id?: string | null): PaperStyleDef | null {
  if (!id) return null;
  return getPaperStyle(id) ?? null;
}

export function listPaperCategories(): { id: PaperStyleDef["category"]; label: string }[] {
  return [
    { id: "ruled", label: "Ruled / Notebook" },
    { id: "grid", label: "Grid / Graph" },
    { id: "school", label: "School / Study" },
    { id: "professional", label: "Professional / Office" },
    { id: "texture", label: "Natural / Texture" },
    { id: "minimal", label: "Minimal / Special" },
  ];
}
