import type { HandwritingStyle, PlanId } from "@/lib/types";
import { styleMinPlan } from "@/lib/plans";

export type HandwritingTheme = {
  id: HandwritingStyle;
  label: string;
  description: string;
  fontClass: string;
  headingClass: string;
  lineHeight: string;
  letterSpacing: string;
  fontSize: string;
  paper: string;
  rule: string;
  marginLine: string;
  highlight: string;
  box: string;
  decoration: "none" | "underline-wavy" | "boxed" | "stars" | "compact" | "ink-bleed" | "journal";
  sample: string;
  minPlan: PlanId;
};

const base = (
  partial: Omit<HandwritingTheme, "minPlan" | "sample"> & { sample?: string },
): HandwritingTheme => ({
  sample: partial.sample || "Study hard. Notes that stick.",
  minPlan: styleMinPlan(partial.id),
  ...partial,
});

export const HANDWRITING_THEMES: Record<HandwritingStyle, HandwritingTheme> = {
  "clean-study": base({
    id: "clean-study",
    label: "Clean Study",
    description: "Clear, upright strokes for everyday studying.",
    fontClass: "font-hand-clean",
    headingClass: "font-hand-clean",
    lineHeight: "1.7",
    letterSpacing: "0.01em",
    fontSize: "1.35rem",
    paper: "#fffdf8",
    rule: "rgba(120, 90, 180, 0.08)",
    marginLine: "rgba(216, 80, 80, 0.35)",
    highlight: "rgba(196, 181, 253, 0.45)",
    box: "rgba(124, 58, 237, 0.12)",
    decoration: "none",
  }),
  "simple-student": base({
    id: "simple-student",
    label: "Simple Student",
    description: "Friendly rounded letters — notebook basics.",
    fontClass: "font-hand-simple",
    headingClass: "font-hand-simple",
    lineHeight: "1.8",
    letterSpacing: "0.02em",
    fontSize: "1.4rem",
    paper: "#fffcf5",
    rule: "rgba(100, 120, 160, 0.1)",
    marginLine: "rgba(200, 90, 90, 0.35)",
    highlight: "rgba(253, 230, 138, 0.5)",
    box: "rgba(148, 163, 184, 0.15)",
    decoration: "none",
  }),
  "neat-notes": base({
    id: "neat-notes",
    label: "Neat Notes",
    description: "Tight classroom handwriting with wavy underlines.",
    fontClass: "font-hand-class",
    headingClass: "font-hand-class",
    lineHeight: "1.85",
    letterSpacing: "0.02em",
    fontSize: "1.3rem",
    paper: "#fffaf0",
    rule: "rgba(90, 140, 200, 0.12)",
    marginLine: "rgba(220, 90, 90, 0.4)",
    highlight: "rgba(253, 224, 71, 0.45)",
    box: "rgba(59, 130, 246, 0.12)",
    decoration: "underline-wavy",
  }),
  "soft-handwritten": base({
    id: "soft-handwritten",
    label: "Soft Handwritten",
    description: "Loose, airy strokes with soft pastel paper.",
    fontClass: "font-hand-aesthetic",
    headingClass: "font-hand-display",
    lineHeight: "1.95",
    letterSpacing: "0.04em",
    fontSize: "1.45rem",
    paper: "#fbf7ff",
    rule: "rgba(167, 139, 250, 0.12)",
    marginLine: "rgba(196, 181, 253, 0.7)",
    highlight: "rgba(244, 114, 182, 0.25)",
    box: "rgba(232, 121, 249, 0.12)",
    decoration: "stars",
  }),
  "exam-notes": base({
    id: "exam-notes",
    label: "Exam Notes",
    description: "Dense, high-contrast revision layout.",
    fontClass: "font-hand-exam",
    headingClass: "font-hand-exam",
    lineHeight: "1.55",
    letterSpacing: "0",
    fontSize: "1.2rem",
    paper: "#f7f7f2",
    rule: "rgba(80, 80, 80, 0.1)",
    marginLine: "rgba(180, 40, 40, 0.45)",
    highlight: "rgba(134, 239, 172, 0.45)",
    box: "rgba(21, 128, 61, 0.12)",
    decoration: "boxed",
  }),
  "realistic-pen": base({
    id: "realistic-pen",
    label: "Realistic Pen",
    description: "Slightly uneven ink — feels like a real ballpoint.",
    fontClass: "font-hand-pen",
    headingClass: "font-hand-pen",
    lineHeight: "1.75",
    letterSpacing: "0.015em",
    fontSize: "1.38rem",
    paper: "#fffef7",
    rule: "rgba(70, 90, 140, 0.09)",
    marginLine: "rgba(190, 60, 60, 0.4)",
    highlight: "rgba(147, 197, 253, 0.4)",
    box: "rgba(51, 65, 85, 0.08)",
    decoration: "ink-bleed",
  }),
  "fine-liner": base({
    id: "fine-liner",
    label: "Fine Liner",
    description: "Thin, precise strokes for diagrams and labels.",
    fontClass: "font-hand-liner",
    headingClass: "font-hand-liner",
    lineHeight: "1.6",
    letterSpacing: "0.03em",
    fontSize: "1.15rem",
    paper: "#fafafa",
    rule: "rgba(0, 0, 0, 0.06)",
    marginLine: "rgba(120, 120, 120, 0.35)",
    highlight: "rgba(167, 243, 208, 0.4)",
    box: "rgba(15, 23, 42, 0.06)",
    decoration: "none",
  }),
  academic: base({
    id: "academic",
    label: "Academic",
    description: "Formal lecture notes with measured spacing.",
    fontClass: "font-hand-academic",
    headingClass: "font-hand-academic",
    lineHeight: "1.7",
    letterSpacing: "0.005em",
    fontSize: "1.28rem",
    paper: "#f8f6f1",
    rule: "rgba(90, 80, 70, 0.08)",
    marginLine: "rgba(140, 50, 50, 0.4)",
    highlight: "rgba(196, 181, 253, 0.35)",
    box: "rgba(88, 28, 135, 0.08)",
    decoration: "boxed",
  }),
  "compact-revision": base({
    id: "compact-revision",
    label: "Compact Revision",
    description: "Dense packing for last-minute review sheets.",
    fontClass: "font-hand-quick",
    headingClass: "font-hand-quick",
    lineHeight: "1.4",
    letterSpacing: "-0.01em",
    fontSize: "1.1rem",
    paper: "#fffbeb",
    rule: "rgba(251, 191, 36, 0.15)",
    marginLine: "rgba(245, 158, 11, 0.45)",
    highlight: "rgba(253, 186, 116, 0.4)",
    box: "rgba(234, 88, 12, 0.1)",
    decoration: "compact",
  }),
  "creative-handwriting": base({
    id: "creative-handwriting",
    label: "Creative Handwriting",
    description: "Expressive flourishes for visual learners.",
    fontClass: "font-hand-creative",
    headingClass: "font-hand-creative",
    lineHeight: "1.9",
    letterSpacing: "0.05em",
    fontSize: "1.5rem",
    paper: "#fdf4ff",
    rule: "rgba(216, 180, 254, 0.2)",
    marginLine: "rgba(192, 132, 252, 0.5)",
    highlight: "rgba(249, 168, 212, 0.35)",
    box: "rgba(168, 85, 247, 0.1)",
    decoration: "stars",
  }),
  "study-journal": base({
    id: "study-journal",
    label: "Study Journal",
    description: "Diary-like pages with soft journal framing.",
    fontClass: "font-hand-journal",
    headingClass: "font-hand-journal",
    lineHeight: "1.85",
    letterSpacing: "0.02em",
    fontSize: "1.32rem",
    paper: "#faf6ef",
    rule: "rgba(120, 100, 80, 0.1)",
    marginLine: "rgba(160, 100, 80, 0.35)",
    highlight: "rgba(254, 215, 170, 0.45)",
    box: "rgba(120, 80, 40, 0.08)",
    decoration: "journal",
  }),
  "detailed-handwriting": base({
    id: "detailed-handwriting",
    label: "Detailed Handwriting",
    description: "Roomy lines for long explanations and proofs.",
    fontClass: "font-hand-detailed",
    headingClass: "font-hand-detailed",
    lineHeight: "2.05",
    letterSpacing: "0.01em",
    fontSize: "1.42rem",
    paper: "#f7f9fc",
    rule: "rgba(100, 130, 180, 0.1)",
    marginLine: "rgba(70, 100, 160, 0.35)",
    highlight: "rgba(186, 230, 253, 0.45)",
    box: "rgba(37, 99, 235, 0.08)",
    decoration: "underline-wavy",
  }),
  "personal-notes": base({
    id: "personal-notes",
    label: "Personal Notes",
    description: "Casual slant — like writing to yourself.",
    fontClass: "font-hand-personal",
    headingClass: "font-hand-personal",
    lineHeight: "1.8",
    letterSpacing: "0.025em",
    fontSize: "1.36rem",
    paper: "#fff9f5",
    rule: "rgba(180, 120, 100, 0.1)",
    marginLine: "rgba(200, 100, 80, 0.4)",
    highlight: "rgba(254, 202, 202, 0.45)",
    box: "rgba(185, 28, 28, 0.06)",
    decoration: "none",
  }),
  "casual-notebook": base({
    id: "casual-notebook",
    label: "Casual Notebook",
    description: "Relaxed, slightly messy desk-notebook look.",
    fontClass: "font-hand-casual",
    headingClass: "font-hand-casual",
    lineHeight: "1.72",
    letterSpacing: "0.01em",
    fontSize: "1.33rem",
    paper: "#f9f7f2",
    rule: "rgba(110, 110, 100, 0.1)",
    marginLine: "rgba(170, 80, 80, 0.35)",
    highlight: "rgba(187, 247, 208, 0.4)",
    box: "rgba(22, 101, 52, 0.08)",
    decoration: "ink-bleed",
  }),
  // Legacy aliases
  clean: base({
    id: "clean",
    label: "Clean (legacy)",
    description: "Legacy clean style.",
    fontClass: "font-hand-clean",
    headingClass: "font-hand-clean",
    lineHeight: "1.7",
    letterSpacing: "0.01em",
    fontSize: "1.35rem",
    paper: "#fffdf8",
    rule: "rgba(120, 90, 180, 0.08)",
    marginLine: "rgba(216, 80, 80, 0.35)",
    highlight: "rgba(196, 181, 253, 0.45)",
    box: "rgba(124, 58, 237, 0.12)",
    decoration: "none",
  }),
  "class-notes": base({
    id: "class-notes",
    label: "Class Notes (legacy)",
    description: "Legacy class notes.",
    fontClass: "font-hand-class",
    headingClass: "font-hand-class",
    lineHeight: "1.85",
    letterSpacing: "0.02em",
    fontSize: "1.3rem",
    paper: "#fffaf0",
    rule: "rgba(90, 140, 200, 0.12)",
    marginLine: "rgba(220, 90, 90, 0.4)",
    highlight: "rgba(253, 224, 71, 0.45)",
    box: "rgba(59, 130, 246, 0.12)",
    decoration: "underline-wavy",
  }),
  aesthetic: base({
    id: "aesthetic",
    label: "Aesthetic (legacy)",
    description: "Legacy aesthetic.",
    fontClass: "font-hand-aesthetic",
    headingClass: "font-hand-display",
    lineHeight: "1.9",
    letterSpacing: "0.03em",
    fontSize: "1.4rem",
    paper: "#fbf7ff",
    rule: "rgba(167, 139, 250, 0.12)",
    marginLine: "rgba(196, 181, 253, 0.7)",
    highlight: "rgba(244, 114, 182, 0.25)",
    box: "rgba(232, 121, 249, 0.12)",
    decoration: "stars",
  }),
  "quick-revision": base({
    id: "quick-revision",
    label: "Quick Revision (legacy)",
    description: "Legacy quick revision.",
    fontClass: "font-hand-quick",
    headingClass: "font-hand-quick",
    lineHeight: "1.5",
    letterSpacing: "-0.01em",
    fontSize: "1.15rem",
    paper: "#fffbeb",
    rule: "rgba(251, 191, 36, 0.15)",
    marginLine: "rgba(245, 158, 11, 0.45)",
    highlight: "rgba(253, 186, 116, 0.4)",
    box: "rgba(234, 88, 12, 0.1)",
    decoration: "compact",
  }),
};

export function getHandwritingTheme(style: HandwritingStyle): HandwritingTheme {
  return HANDWRITING_THEMES[style] || HANDWRITING_THEMES["clean-study"];
}

export const SELECTABLE_STYLES: HandwritingStyle[] = [
  "clean-study",
  "simple-student",
  "neat-notes",
  "soft-handwritten",
  "exam-notes",
  "realistic-pen",
  "fine-liner",
  "academic",
  "compact-revision",
  "creative-handwriting",
  "study-journal",
  "detailed-handwriting",
  "personal-notes",
  "casual-notebook",
];
